# Arista EOS - R1 initial validation
# R1 = 172.20.20.14

[[inputs.gnmi]]
  addresses = [
    "172.20.20.14:6030", # R1
    "172.20.20.5:6030",  # R2
    "172.20.20.12:6030", # R5
    "172.20.20.8:6030",  # S1
    "172.20.20.11:6030", # S2
    "172.20.20.7:6030"   # S3
  ]

  username = "$ARISTA_USERNAME"
  password = "$ARISTA_PASSWORD"

  # EOS gNMI is running without TLS in this lab.
  tls_enable = false

  # Arista can omit the prefix/path information in some updates.
  path_guessing_strategy = "subscription"

  [[inputs.gnmi.subscription]]
    name = "arista_ifcounters"
    path = "/interfaces/interface/state/counters"
    subscription_mode = "sample"
    sample_interval = "5s"
