# Arista EOS - Tier 3 routing telemetry
# IS-IS adjacency state for R1, R2, S1, S2

[[inputs.gnmi]]
  addresses = [
    "172.20.20.14:6030", # R1
    "172.20.20.5:6030",  # R2
    "172.20.20.8:6030",  # S1
    "172.20.20.11:6030"  # S2
  ]

  username = "$ARISTA_USERNAME"
  password = "$ARISTA_PASSWORD"

  tls_enable = false
  redial = "10s"

  path_guessing_strategy = "subscription"

  [[inputs.gnmi.subscription]]
    name = "arista_isis_adj"
    path = "/network-instances/network-instance[name=default]/protocols/protocol/isis/interfaces/interface/levels/level/adjacencies/adjacency/state"
    subscription_mode = "sample"
    sample_interval = "10s"
